### PR TITLE
Docs: Add screenshot for json form editor widget

### PR DESCRIPTION
**Pull request by zeusdeux**

### CODE REVIEW

**Comment by DanweDE** [comment]
Why is there so much noise in the screenshot's path. Thomas' chessbord.gif path looks much nicer:
`http://contentful.github.io/widget-sdk/assets/chessboard.gif`

**Comment by zeusdeux** [comment]
That is because I am using github cloud to store the images instead of polluting the repository itself.

**Comment by DanweDE** [comment]
I think same holds true for Thomas' link. It does not reside in the repo itself. Just have a look.

**Comment by zeusdeux** [comment]
@DanweDE Fixed for all docs PRs.

**Pull request merged**
