### PR TITLE
Slug widget: Fix broken slug editor

### PR DESCRIPTION
**Pull request by zeusdeux**
Fix:

- Wrong method names
- Race conditions due to api not being loaded before the widget entry point was called
- How duplicates were looked up (this wasn't working at all)

Refactor:

- Rewrite using ES2015 to keep it consistent with other widgets
- Abstract away change handling into a function
- Rename functions based on what they do
- Added comments

### CODE REVIEW

**Comment by DanweDE** [comment]
Would be nice to have a quick summary in the commit msg what's been broken.

**Comment by zeusdeux** [comment]
@danweDE added the changes in the PR description. Will that suffice?

**Comment by DanweDE** [comment]
@zeusdeux Very nice elaborate summary but the best place for it would be the commit message so it's visible when browsing the `git log`.

**Comment by zeusdeux** [comment]
@DanweDE done!

**Comment by DanweDE** [comment]
> Rewrite using ES2015 to keep it consistent with other widgets

nice, but keep in mind that we chose to implement all widgets a little differently to show diverse ways of doing things. So consistency was never a requirement here.

**Comment by zeusdeux** [comment]
@DanweDE I was talking about this with @floelhoeffel and he suggested that we show one solid way of doing stuff rather than many different approaches so that people can get up and running quicker. 
That is also the reason why I am moving our builds to browserify + babelify in most places. Converging it all into an approach that people can follow out of the box.

**Pull request merged**
